#!/bin/sh
python3 main.py car/train.csv 1
python3 main.py car/train.csv 2
python3 main.py car/train.csv 3
python3 main.py car/train.csv 4
python3 main.py car/train.csv 5
python3 main.py car/train.csv 6
python3 mainmajority.py car/train.csv 1
python3 mainmajority.py car/train.csv 2
python3 mainmajority.py car/train.csv 3
python3 mainmajority.py car/train.csv 4
python3 mainmajority.py car/train.csv 5
python3 mainmajority.py car/train.csv 6
python3 maingini.py car/train.csv 1
python3 maingini.py car/train.csv 2
python3 maingini.py car/train.csv 3
python3 maingini.py car/train.csv 4
python3 maingini.py car/train.csv 5
python3 maingini.py car/train.csv 6